---
kind: Template
apiVersion: v1

objects:
  kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    creationTimestamp: null
    labels:
      app: magento2-qa
      name: magento2-qa-web
    name: magento2-qa-web
  spec:
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: magento2-qa
          name: magento2-qa-web
      spec:
        containers:
        - name: magento2-qa-web
          image: metrilo.azurecr.io/metrilo/magento2-plugin:$(RELEASE_VERSION)

parameters:
  - name: RELEASE_VERSION
    description: "Release version"
    required: true
    parameterType: string
