---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: magento2-qa
  name: magento2-qa-service

spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 80
  selector:
    app: magento2-qa
    name: magento2-qa-web
  type: LoadBalancer

status:
  loadBalancer: {}
